baseURL = "https://br-brasil.github.io/LeituraBR/"
canonifyURLs = true
relativeURLs = false
publishDir = "public"
languageCode = "pt-br"
title = "LeituraBR"
paginate = 10

[params]
  description = "Landing page para venda de livros no Brasil"
  author = "LeituraBR"

[outputs]
  home = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
